### ISSUE TITLE
Laravel Nova now includes native support for longitude and latitude

### ISSUE THREAD

**Issue by peterchrjoergensen** [Silvanite/nova-field-place#1]
It was added in v1.2.0, which renders this package obsolete in any versions equal to or higher. 

Should've been in there from the start. ¯\\_(ツ)_/¯

Thanks!

**Comment by m2de** [comment]
Thanks @peterchrjoergensen. Yeah I was aware of this finally making it into the main Nova repo. Will update the readme to reflect this. Cheers.

**Comment by peterchrjoergensen** [comment]
Awesome. 👍
